//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public long Id { get; set; }
        public long VehicleId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string InvoiceNumber { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
