//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public long Id { get; set; }
        public long VehicleId { get; set; }
        public long ClientId { get; set; }
        public Nullable<long> ReservedBy { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
