//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePhotos
    {
        public long Id { get; set; }
        public long VehicleId { get; set; }
        public string PhotoPath { get; set; }
        public bool IsMain { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Vehicles Vehicles { get; set; }
    }
}
